name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event
        run: echo "Event = ${{ github.event_name }}"

      - name: Echo Branch
        run: echo "Branch = ${{ github.ref }}"

      - uses: actions/checkout@v3

      - name: List files in the repository
        run: ls
